### ISSUE TITLE
Location API 405 Method Not Allowed

### ISSUE THREAD

**Issue by thejasonxie** [ChainXY/ChainXY_API#3]
## Description
I am getting 405 Method Not Allowed error when calling the Locations API from my web app but on Postman, it works. See below for code example and pictures. My web app is a ReactJS application. 

The error caught is "TypeError: NetworkError when attempting to fetch resource." as you can see in the image of console below. Not sure if this is an issue with the API or my web app. Thanks for the help!

## Example
**API URL I want to call**:
https://location.chainxy.com/api/Locations?north=33&east=-96&south=32&west=-97&chainId=4539&query={"ChainLocation/FirstAppeared":">08/25/2022"}

**Here's the code example**:
```js
const getChainLocation = async (params) => {
  try {
    const query = encodeURIComponent(
      `"ChainLocation/FirstAppeared":">${params.firstappeared}"`
    );
    const response = await fetch(
      `https://location.chainxy.com/api/Locations?north=${params.north}&east=${params.east}&south=${params.south}&west=${params.west}&chainIds=${params.chainids}&query={${query}}`,
      {
        method: "GET",
        headers: {
          "x-apikey": "my api key",
          "Content-Type": "application/json",
          "Access-Control-Allow-Origin": "*",
        },
      }
    );

    console.log("response: ", response);
  } catch (err) {
    console.log("err:", err);
  }
};

getChainLocation({
  north: 33,
  east: -96,
  south: 32,
  west: -97,
  chainids:"4539",
  firstappeared: "08/25/2022"
})
```
**Here's the errors from my web app**:

![Screenshot 2023-05-25 at 10 07 32 PM](https://github.com/ChainXY/ChainXY_API/assets/34463193/28c0d4d8-03fa-46af-b688-92056e00ff46)

**Successful fetch from Postman**:

<img width="943" alt="Screenshot 2023-05-25 at 10 11 21 PM" src="https://github.com/ChainXY/ChainXY_API/assets/34463193/fc502f24-48a7-4b52-8a8f-0cf095ac0cdd">

**Comment by rrydv** [comment]
hi Jason, copying the response from the email here for record. 

This is not an issue with the API, but rather with the use case. We are not planning to expose our API as a direct integration with third-party applications (i.e. allow CORS requests, which is the underlying issue here). 

We make no guarantees regarding the uptime of the API, so it is preferable for you to set up an integration where ChainXY data is downloaded, and then managed by a backend on your side. Otherwise, you’re likely to run into scenarios where the API might be unavailable/slow which will hinder usability of your application. 

We might revise this in the future, but it would require significant changes to the design of our application/infrastructure.

will close the issue for now, as this is out of scope for current API integration.
